import {
  FaGithub,
  FaLinkedin,
  FaFacebook,
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaNode,
  FaGitAlt,
  FaDocker,
  FaCode,
  FaCheckCircle,
  FaImage,
  FaMapMarkerAlt,
  FaTrophy,
  FaStar,
  FaAward,
  FaTag,
  FaMedal,
  FaLaptopCode,
  FaEnvelope,
  FaExternalLinkAlt,
  FaTachometerAlt,
  FaCog,
  FaProjectDiagram,
  FaBriefcase,
  FaGraduationCap,
  FaLayerGroup,
  FaListAlt,
  FaTimes,
  FaPlus,
  FaArrowRight,
  FaEye,
  FaEyeSlash,
  FaSun,
  FaMoon,
  FaLaptop,
  FaSlidersH,
  FaChartBar,
  FaDownload,
} from "react-icons/fa";
import { SiMongodb, SiExpress, SiViblo, SiPostgresql, SiTypescript, SiPython, SiTailwindcss } from "react-icons/si";
import { MdEmail } from "react-icons/md";
import { RiNextjsFill } from "react-icons/ri";
import {
  Layout,
  Target,
  ShieldCheck,
  Code2,
  Compass,
  Camera,
  Smartphone,
  PenTool,
} from "lucide-react";

// Curated registry of icons addressable by the string names stored in the DB.
const REGISTRY = {
  FaGithub,
  FaLinkedin,
  FaFacebook,
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaNode,
  FaGitAlt,
  FaDocker,
  FaCode,
  FaCheckCircle,
  FaImage,
  FaMapMarkerAlt,
  FaTrophy,
  FaStar,
  FaAward,
  FaTag,
  FaMedal,
  FaLaptopCode,
  FaEnvelope,
  FaExternalLinkAlt,
  FaTachometerAlt,
  FaCog,
  FaProjectDiagram,
  FaBriefcase,
  FaGraduationCap,
  FaLayerGroup,
  FaListAlt,
  FaTimes,
  FaPlus,
  FaArrowRight,
  FaEye,
  FaEyeSlash,
  FaSun,
  FaMoon,
  FaLaptop,
  FaSlidersH,
  FaChartBar,
  FaDownload,
  SiMongodb,
  SiExpress,
  SiViblo,
  SiPostgresql,
  SiTypescript,
  SiPython,
  SiTailwindcss,
  MdEmail,
  RiNextjsFill,
  Layout,
  Target,
  ShieldCheck,
  Code2,
  Compass,
  Camera,
  Smartphone,
  PenTool,
};

export default function Icon({ name, className = "", ...props }) {
  const Component = REGISTRY[name] || FaTag;
  return <Component className={className} {...props} aria-hidden="true" />;
}
